### ISSUE TITLE
Tracking issue for unstable features

### ISSUE THREAD

**Issue by Nadrieril** [Nadrieril/dhall-rust#51]
- [x] [box_patterns](https://doc.rust-lang.org/nightly/unstable-book/language-features/box-patterns.html): For nested matching. Removed a while ago and replaced with `ExprF` and appropriate (un)rolling.
- [x] [slice_patterns](https://doc.rust-lang.org/nightly/unstable-book/language-features/slice-patterns.html): Used a lot in binary decoder. Would be a huge pain to do without.
- [x] [proc_macro_hygiene](https://doc.rust-lang.org/nightly/unstable-book/language-features/proc-macro-hygiene.html). Enables `dhall::expr!()` and friends in expressions. Can be circumvented; see https://github.com/Nadrieril/dhall-rust/issues/52.
- [x] [bind_by_move_pattern_guards](https://doc.rust-lang.org/unstable-book/language-features/bind-by-move-pattern-guards.html): Used to avoid https://github.com/rust-lang/rust/issues/59803. Removed in https://github.com/Nadrieril/dhall-rust/commit/350d92430a047a41f855c9f61d278c4476f04d78.
- [x] [custom_inner_attributes](https://doc.rust-lang.org/unstable-book/language-features/custom-inner-attributes.html): Used to prevent rustfmt from messing up the list of tests. Will be removed when the test lists gets generated automatically.
- [x] [label_break_value](https://doc.rust-lang.org/unstable-book/language-features/label-break-value.html#label_break_value): Mild convenience; could be easily removed.
- [x] [non_exhaustive](https://doc.rust-lang.org/beta/unstable-book/language-features/non-exhaustive.html): Used to somewhat limit API surface; could be easily removed.
- [x] [inner_deref](https://doc.rust-lang.org/nightly/unstable-book/library-features/inner-deref.html): just for convenience.
- [x] [never_type](https://doc.rust-lang.org/unstable-book/language-features/never-type.html): convenience, alternative is rolling own empty enum. Should get stabilized eventually.
- [x] [try_blocks](https://doc.rust-lang.org/unstable-book/language-features/try-blocks.html): For parser macros. Could be avoided using anonymous closures.
- [x] [exhaustive_patterns](https://doc.rust-lang.org/unstable-book/language-features/exhaustive-patterns.html): Small convenience. Could be traded for some verbosity.
- [x] [proc_macro_hygiene](https://doc.rust-lang.org/nightly/unstable-book/language-features/proc-macro-hygiene.html): Used in parser. Would need some advanced hackery to do without.
- [x] [drain_filter](https://doc.rust-lang.org/nightly/unstable-book/language-features/drain-filter.html): Small convenience. Could be traded for some verbosity.
- [x] type_alias_enum_variant: has been stabilized in 1.37.0
