### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Nadrieril** [Nadrieril/dhall-rust#74]
https://doc.rust-lang.org/nightly/book/ch14-02-publishing-to-crates-io.html

**Comment by Nadrieril** [comment]
- [ ] abnf_to_pest: blocked on https://github.com/duesee/abnf/issues/1
- [ ] dhall
- [ ] dhall_generated_parser
- [ ] dhall_core
- [ ] dhall_generator
- [ ] improved_slice_patterns

**Comment by Nadrieril** [comment]
The main blockers right now are:
- decent messages for all type errors
- check whether merging `dhall_generated_parser` with `dhall_syntax` kills compile times or not
- decide whether keeping `dhall_syntax` and `dhall` split makes sense

**Comment by Nadrieril** [comment]
Done ! https://crates.io/crates/serde_dhall
