### ISSUE TITLE
Tracking issue for missing features

### ISSUE THREAD

**Issue by Nadrieril** [Nadrieril/dhall-rust#77]
#### Dhall spec
  - [ ] parsing
    - [x] nullary union constructors #36
    - [x] selection by expression #94
    - [x] `toMap` #96
    - [x] inline headers
    - [ ] RFC3986 URLs #136 
    - [x] everything else
  - [ ] imports
    - [x] import cycles #8
    - [x] import alternatives #70
    - [x] import canonicalization #76
    - [x] remote imports #10
    - [x] sanity check in remote imports #139
    - [ ] headers in remote imports #134 
    - [ ] checksums #135 
    - [x] `as Location` #139
    - [ ] ...
  - [ ] typechecking
    - [x] text interpolation
    - [x] higher-kinded records
    - [x] unions
    - [x] `Integer/show`
    - [x] `Natural/show`
    - [x] `Double/show`
    - [x] `Natural/toInteger`
    - [x] `#`, aka `ListAppend`
    - [x] `Text/show`
    - [x] `//\\`, aka `CombineTypes` and `RecursiveRecordTypeMerge` #91 
    - [x] `/\`, aka `Combine` and `RecursiveRecordMerge` #89
    - [x] `//`, aka `Prefer` and `RightBiasedRecordMerge` #86
    - [x] record projection (`record.{ x, y, z }`)
    - [x] union constructor selection (`union.x`)
    - [x] nullary union constructors #36
    - [x] merge
    - [x] duplicate record fields
    - [x] selection by expression #94
    - [x] `toMap` #96
    - [ ] ...
  - [ ] normalization
    - [x] text interpolation
    - [x] `Integer/show`
    - [x] `Natural/show`
    - [x] `Double/show`
    - [x] `Natural/toInteger`
    - [x] `#`, aka `ListAppend`
    - [x] `Text/show`
    - [x] `//\\`, aka `CombineTypes` and `RecursiveRecordTypeMerge`
    - [x] `/\`, aka `Combine` and `RecursiveRecordMerge`
    - [x] `//`, aka `Prefer` and `RightBiasedRecordMerge`
    - [x] record projection (`record.{ x, y, z }`)
    - [x] union constructor selection (`union.x`)
    - [x] nullary union constructors #36
    - [x] various simplifications
    - [x] simplifications that use equivalence
    - [x] selection by expression #94
    - [x] Normalize field selection further by inspecting the argument #139
    - [x] `toMap` #96
    - [ ] ...
  - [x] alpha-normalization #12
  - [x] binary decoding
  - [x] binary encoding #39

#### Pretty error messages
  - [ ] parsing
    - [x] show error location in source file
    - [ ] explain the error in words
  - [ ] import
  - [ ] typecheck
    - [x] basic legible error message #63
    - [x] show error location in source file #40
  - [ ] binary decoding
  - [ ] explain the cause of error in the global `Error` type

#### Public API
  - [ ] control import resolution
  - [ ] deserialize from file
  - [x] ~settle lifetime behaviour in expr lifecycle~
  - [ ] documentation
    - [x] document nightlyness
    - [x] deserialization functions
    - [x] ~expression lifecycle~
    - [ ] ...
  - [x] publish to crates.io #74
  - [x] split the public API into a separate crate

**Comment by FintanH** [comment]
Hey @Nadrieril is there any low hanging fruit where I could get started here? I'm new to Rust, but familiar with Dhall and have contributed to the language and Haskell implementation. Willing to get my hands dirty here 🙇

**Comment by Nadrieril** [comment]
Hey @FintanH ! Thanks for your interest in this project ! I'm glad you're willing to get your hands dirty because this project is quite a mess ^^
I can't see anything very low-hanging sadly. Would you be interested in trying one of the missing typechecking cases, say right-biased record merge for example ? I think it could make a nice mini-project

**Comment by FintanH** [comment]
Ya, I can give it a shot! :)

**Comment by Nadrieril** [comment]
Yay ! Could you open an issue about that feature ? Then over there you can bombard me with questions about the structure of the project, where the different bits are, how `Value`s and `Thunk`s work, or anything else you need. I'll try to answer as much as I'm able to.
As a start I'd recommend you try to break something in `typecheck.rs` and run `cargo test`, to help you get an idea of the thing.

**Comment by Nadrieril** [comment]
@basile-henry: if you're interested too, you're welcome to try recursive record merge for example. Just open an issue too and ask away !

**Comment by basile-henry** [comment]
@Nadrieril I might have a go at recursive record merge this weekend if no one has started working on that by then! :smile:

**Comment by FintanH** [comment]
You can link the issue to the checklist if you want now :) https://github.com/Nadrieril/dhall-rust/issues/86

**Comment by FintanH** [comment]
I've created an issue for `Combine` https://github.com/Nadrieril/dhall-rust/issues/89. @basile-henry Did you start work on it? If not I could get cracking on it.

**Comment by basile-henry** [comment]
@FintanH I did start working on it but I didn't get very far. The codebase has changed quite a bit since last time I looked at it and I was struggling to find all the pieces I needed.
Feel free to take it over, you probably know more than I do about how everything fits together by now.
This is what I started doing, it's still very incomplete but maybe it'll help you getting started on that one: https://github.com/basile-henry/dhall-rust/commit/3b49079625909436f6800b0c93af2f602d41db39

**Comment by FintanH** [comment]
@Nadrieril I'm feeling some momentum after putting up those PRs for typechecking. What would make the most sense for working on next? :grin:

**Comment by Nadrieril** [comment]
@FintanH :D
Let's see... The missing features are essentially about imports. There's a lot to do: we barely support local imports. You can pick what you want in there: remote imports, environment variables, checksums, import alternatives, ... Import alternatives may require some tinkering with the overengineered mess I made around ExprF, so you probably want to avoid that until I sort out the mess; the rest should be fine.

**Comment by FintanH** [comment]
I was thinking import would be next too. I'll do up some tickets and do some digging!

**Comment by Nadrieril** [comment]
There's a new feature to implement: selection by expression (https://github.com/Nadrieril/dhall-rust/issues/94) ! There's everything from parsing to typechecking left to implement, if anyone's interested

**Comment by Nadrieril** [comment]
@basile-henry @FintanH I've given both of you merge rights to this repo, so that you can merge your own PRs yourselves :). Here is what I propose: you can merge a PR yourself after I've approved it, or otherwise if I haven't approved or disapproved for 7 days you can go ahead and merge it (like what's done in `dhall-lang`). Mistakes are easy to fix, so we may as well err on the side of making things happen.

**Comment by FintanH** [comment]
Ya that sounds great. Thanks!

**Comment by Nadrieril** [comment]
I wrote one or two [good first issues](https://github.com/Nadrieril/dhall-rust/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) is anyone is interested :)

**Comment by Nadrieril** [comment]
Now that most features are done, I'm closing this in favor of labeled issues https://github.com/Nadrieril/dhall-rust/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Astandard-compliance
